name: mocker
description: "Mocker is a tool for generating mock data for the Smart Sampus UIS project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared:
    path: ../../shared
  web_socket_channel: ^3.0.1
  flutter_adaptive_scaffold: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_syntax_view: ^4.1.4
  flex_color_scheme: ^8.0.2
  gap: ^3.0.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  get_it: ^8.0.3
  logger: ^2.5.0
  go_router: ^14.6.3
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  uuid: ^4.5.1
  dropdown_button2: ^2.3.9
  file_saver: ^0.2.14
  file_picker: ^8.1.7
  fl_chart: ^0.70.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  web:
    generate: true
    image_path: "web/icon.png"

flutter:
  uses-material-design: true
