services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  mosquitto:
    image: 'eclipse-mosquitto:latest'
    container_name: 'mosquitto'
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
