services:

  database:
    image: 'mongo:latest'
#    ports:
#      - "27017:27017"
    networks:
      - smart_campus_core_iot_campus_uis
    volumes:
      - mongo_data:/data/db

  server:
    image: 'pholluxion/mocker-server:latest'
    depends_on:
      - database
    environment:
        - MONGO_HOST=database
        - MONGO_PORT=27017
        - MONGO_DB=iot
    ports:
      - "8090:8090"
    networks:
      - smart_campus_core_iot_campus_uis

  web:
#    build: ./web
    image: 'pholluxion/mocker-web:latest'
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - smart_campus_core_iot_campus_uis

networks:
  smart_campus_core_iot_campus_uis:
    external: true

volumes:
    mongo_data: