services:
  server:
    image: 'pholluxion/mocker-server:latest'
    environment:
        - MONGO_HOST=mongo
        - MONGO_PORT=27017
        - MONGO_DB=iot
    ports:
      - "8090:8090"
    networks:
      - smart_campus_core_iot_campus_uis

networks:
  smart_campus_core_iot_campus_uis:
    external: true

volumes:
  mocker-data:
    driver: local