services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    networks:
      - mocker-network
    volumes:
      - mocker-data:/data/db

  server:
    image: 'pholluxion/mocker-server:latest'
    environment:
        - MONGO_HOST=mongodb
        - MONGO_PORT=27017
        - MONGO_DB=mocker
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
    networks:
      - mocker-network

networks:
  mocker-network:
    driver: bridge

volumes:
  mocker-data:
    driver: local