services:

  database:
    image: 'mongo:latest'
    networks:
      - mocker
    volumes:
      - mongo_data:/data/db

  server:
    image: 'pholluxion/mocker-server:latest'
    depends_on:
      - database
    environment:
        - MONGO_HOST=database
        - MONGO_PORT=27017
        - MONGO_DB=iot
    ports:
      - "8090:8090"
    networks:
      - mocker
      - smart_campus_workshop_iot_campus_uis

  web:
    image: 'pholluxion/mocker-web:latest'
    depends_on:
      - server
    ports:
      - "3000:80"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped
    networks:
      - mocker

networks:
  smart_campus_workshop_iot_campus_uis:
    external: true
  mocker:
    driver: bridge

volumes:
    mongo_data: