name: shared
description: A library for common functionality used by all other packages.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  uuid: ^4.5.1
  intl: ^0.19.0
  yaml_edit: ^2.2.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
